name: Ubuntu

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok

    - name: Auth
      run: ngrok config add-authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Install XRDP & XFCE
      run: sudo apt install xrdp -y
    - run: sudo systemctl start xrdp
    - run: sudo adduser --disabled-password --gecos "" amon
    - run: sudo usermod --password $(echo PassWord69! | openssl passwd -1 -stdin) amon
    - run: sudo usermod -aG sudo amon
    - name: Create Tunnel
      run: ngrok tcp 3389
